title: Heroic Webcraft
email: lh-chan@mechapilot.org
description: > # this means to ignore newlines until "baseurl:"
  Web design by Chaney.
baseurl: "/heroic-jekyll" # the subpath of your site, e.g. /blog
url: "http://cybersenshi.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: cybersenshi
github_username:  cybersenshi
google_analytics:

# Build settings
markdown: kramdown
include: ["_pages"]
permalink: /:title/
exclude:
  - Gemfile
  - Gemfile.lock
