title: Heroic Webcraft
email: lh-chan@mechapilot.org
description: > # this means to ignore newlines until "baseurl:"
  Web design by Chaney.
baseurl: "/heroic-jekyll" # the subpath of your site, e.g. /blog
url: "https://cybersenshi.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: cybersenshi
github_username:  cybersenshi

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
